"""Marketplace endpoints — browse and install AiSOC marketplace items.

The marketplace ships as a single static index (``marketplace/index.json``)
generated by ``scripts/build_marketplace.py`` from the on-disk
``detections/``, ``playbooks/``, and ``plugins/`` trees.

Authorization
-------------
Install and uninstall require ``settings:write``. One permission covers all
three item types because one route does: ``body.type`` is
``detection | playbook | plugin``, so the permission has to be the ceiling of
the three rather than the floor, and turning tenant-wide content on or off is
tenant configuration. The per-type permissions live on ``community.py``,
where each route handles exactly one type.

The catalogue already refused reference-only items over the console's
objections — that check was load-bearing because a POST straight at this
route bypassed a button styled as disabled. This closes the other half: the
caller's entitlement, not just the item's.

This module provides a thin HTTP surface so the web UI can:

- Read the index server-side (``GET /v1/marketplace``)
- Filter by MITRE ATT&CK technique (``GET /v1/marketplace?mitre=T1078``)
- Install an item to the active tenant
  (``POST /v1/marketplace/install`` body=``{type,id}``)
- Read which items are currently installed for the tenant
  (``GET /v1/marketplace/installed``)

Install state is intentionally tracked in-memory per process for now —
the marketplace UI's “✓ Installed” affordance is the main consumer, and a
heavier per-tenant ``installed_items`` table can replace this without an
API contract change. The ``content_sha256`` field returned at install time
gives the UI something stable to display and lets us evolve to a DB-backed
store later.
"""

from __future__ import annotations

import hashlib
import json
import threading
from pathlib import Path
from typing import Annotated, Any, Literal

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy import text

from app.api.v1.deps import AuthUser, require_permission
from app.db.rls import TenantDBSession
from app.services import marketplace_installs

router = APIRouter(prefix="/marketplace", tags=["marketplace"])

# ── Locating the on-disk index ────────────────────────────────────────────────

# On the host this file lives at services/api/app/api/v1/endpoints/marketplace.py
# so the repo root is six levels up. Inside the API Docker image only the
# /app/app/... subtree is copied, so parents[6] would IndexError. We resolve
# the deepest available ancestor and rely on the absolute container paths
# below as a safety net.
_HERE = Path(__file__).resolve()
_HERE_PARENTS = list(_HERE.parents)
_REPO_ROOT = _HERE_PARENTS[6] if len(_HERE_PARENTS) > 6 else _HERE_PARENTS[-1]

#: The copy that travels inside the image.
#:
#: Every path below it is outside the API's Docker build context — the image
#: is built from `services/api`, so `COPY . .` never saw the repository-root
#: `marketplace/` directory, none of the four original candidates existed at
#: runtime, and the marketplace answered 503 on every containerised
#: deployment. That is what discussion #374 reported, and it was true of every
#: release since this endpoint was written.
#:
#: `scripts/build_marketplace.py` writes this alongside the other two copies
#: and `scripts/check_marketplace_index_parity.py` keeps them byte-identical,
#: so this cannot drift into describing a different catalogue than the console
#: shows.
_PACKAGED_INDEX = _HERE_PARENTS[3] / "data" / "marketplace" / "index.json"

_CANDIDATE_PATHS = [
    # A source checkout wins, so a contributor regenerating the index sees the
    # change without rebuilding the image.
    _REPO_ROOT / "marketplace" / "index.json",
    _REPO_ROOT / "apps" / "web" / "public" / "marketplace" / "index.json",
    Path("/app/marketplace/index.json"),
    Path("/app/apps/web/public/marketplace/index.json"),
    _PACKAGED_INDEX,
]


def _resolve_index_path() -> Path:
    for p in _CANDIDATE_PATHS:
        if p.exists():
            return p
    raise HTTPException(
        status_code=503,
        detail=("marketplace/index.json not found. Run `pnpm marketplace:build` to generate it."),
    )


_index_cache: dict[str, Any] = {"path": None, "mtime": 0.0, "data": None}
_index_lock = threading.Lock()


def _load_index() -> dict[str, Any]:
    """Load (and lazily refresh) the on-disk marketplace index."""
    path = _resolve_index_path()
    mtime = path.stat().st_mtime
    with _index_lock:
        if _index_cache["data"] is None or _index_cache["path"] != str(path) or _index_cache["mtime"] != mtime:
            try:
                _index_cache["data"] = json.loads(path.read_text(encoding="utf-8"))
            except Exception as exc:
                raise HTTPException(
                    status_code=500,
                    detail=f"Failed to parse marketplace index: {exc}",
                ) from exc
            _index_cache["path"] = str(path)
            _index_cache["mtime"] = mtime
        return _index_cache["data"]


# ── Per-tenant installed state ────────────────────────────────────────────────

# Keyed by (tenant_id, type, item_id) → install record. Replace with a real
# table when we move installed-set tracking into Postgres.


def _resolve_item_path(item: dict[str, Any]) -> Path:
    """Resolve a marketplace item's on-disk path safely.

    The ``rel`` value comes from ``marketplace/index.json``, which is
    generated by ``scripts/build_marketplace.py`` and *should* only ever
    contain relative paths inside ``detections/``, ``playbooks/``, or
    ``plugins/``. We still validate defensively so a tampered or
    misgenerated index can't be used to read arbitrary files via
    ``../../etc/passwd`` style entries.
    """
    rel = item.get("path")
    if not rel or not isinstance(rel, str):
        raise HTTPException(
            status_code=500,
            detail=f"Marketplace item {item.get('id')} has no path field",
        )

    rel_path = Path(rel)
    if rel_path.is_absolute() or any(part == ".." for part in rel_path.parts):
        # Either an absolute path or one with parent-directory traversal —
        # neither is ever legitimate for an index entry.
        raise HTTPException(
            status_code=400,
            detail="Invalid marketplace item path",
        )

    # Items must live under one of these trees. Anything else is rejected,
    # even if it resolves to a real file on disk.
    _ALLOWED_SUBDIRS = ("detections", "playbooks", "plugins")
    if rel_path.parts and rel_path.parts[0] not in _ALLOWED_SUBDIRS:
        raise HTTPException(
            status_code=400,
            detail="Marketplace items must live under detections/, playbooks/, or plugins/",
        )

    def _is_within(child: Path, parent: Path) -> bool:
        try:
            child.relative_to(parent)
        except ValueError:
            return False
        return True

    candidate_roots = [_REPO_ROOT, Path("/app")]
    for root in candidate_roots:
        resolved_root = root.resolve()
        target = (root / rel_path).resolve()
        if not _is_within(target, resolved_root):
            # Symlink games or odd resolution — refuse to serve.
            continue
        if target.exists():
            return target

    raise HTTPException(
        status_code=404,
        detail=f"Marketplace item file missing on disk: {rel}",
    )


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _content_sha256(item: dict[str, Any]) -> str:
    """The item's digest, from disk when the file is there and the index when not.

    Hashing the file was the only route until now, and the API image carries
    neither `detections/`, `playbooks/` nor `plugins/` — it is built from
    `services/api`, which contains none of them. So an install in a container
    failed on a missing file even once the index itself was found.

    `scripts/build_marketplace.py` now records each item's SHA-256 while it
    reads the file it is indexing, which makes the index self-describing. The
    on-disk read still wins where the trees exist, so a contributor editing a
    rule in a checkout gets the digest of what they just edited rather than
    the one the index was generated from.
    """
    try:
        return _hash_file(_resolve_item_path(item))
    except HTTPException:
        recorded = item.get("sha256")
        if isinstance(recorded, str) and recorded:
            return recorded
        raise


# ── Schemas ───────────────────────────────────────────────────────────────────


class InstallRequest(BaseModel):
    type: Literal["detection", "playbook", "plugin"]
    id: str = Field(..., min_length=1, max_length=200)


class InstallResponse(BaseModel):
    id: str
    type: str
    name: str
    version: str
    content_sha256: str
    installed_at: str
    installed_by: str
    already_installed: bool = False


class MarketplaceItemSummary(BaseModel):
    id: str
    type: str
    name: str
    description: str = ""
    version: str = "1.0.0"
    severity: str | None = None
    category: str | None = None
    source: str = "core"
    verified: bool = False
    sdks: list[str] = []
    mitre_techniques: list[str] = []
    tags: list[str] = []


class MarketplaceListResponse(BaseModel):
    total: int
    stats: dict[str, Any]
    mitre_coverage: dict[str, Any]
    items: list[MarketplaceItemSummary]
    installed_ids: list[str]


# ── Endpoints ─────────────────────────────────────────────────────────────────


@router.get("", response_model=MarketplaceListResponse)
async def list_marketplace(
    current_user: AuthUser,
    db: TenantDBSession,
    type_filter: Literal["detection", "playbook", "plugin"] | None = Query(None, alias="type"),
    mitre: str | None = Query(
        None,
        description="MITRE ATT&CK technique ID, e.g. T1078 or T1078.004",
    ),
    severity: str | None = Query(None),
    category: str | None = Query(None),
    source: Literal["core", "community"] | None = Query(None),
    sdk: Literal["python", "go", "both"] | None = Query(None),
    search: str | None = Query(None, max_length=200),
) -> MarketplaceListResponse:
    """Return the marketplace index with the same filters the UI exposes."""
    idx = _load_index()
    items: list[dict[str, Any]] = list(idx.get("items") or [])

    if type_filter:
        items = [i for i in items if i.get("type") == type_filter]
    if severity:
        items = [i for i in items if i.get("severity") == severity]
    if category:
        items = [i for i in items if i.get("category") == category]
    if source:
        items = [i for i in items if (i.get("source") or "core") == source]
    if mitre:
        mid = mitre.upper()
        items = [i for i in items if mid in (i.get("mitre_techniques") or [])]
    if sdk:
        kept: list[dict[str, Any]] = []
        for it in items:
            if it.get("type") != "plugin":
                continue
            sdks = it.get("sdks") or []
            if sdk == "both" and not ("python" in sdks and "go" in sdks):
                continue
            if sdk in ("python", "go") and sdk not in sdks:
                continue
            kept.append(it)
        items = kept
    if search:
        q = search.lower()
        items = [
            i
            for i in items
            if q in (i.get("name") or "").lower()
            or q in (i.get("description") or "").lower()
            or any(q in (t or "").lower() for t in (i.get("tags") or []))
            or any(q in (m or "").lower() for m in (i.get("mitre_techniques") or []))
            or q in (i.get("id") or "").lower()
        ]

    tenant_id = str(current_user.tenant_id)
    installed_ids = await marketplace_installs.installed_item_ids(db, tenant_id=tenant_id)

    return MarketplaceListResponse(
        total=len(items),
        stats=idx.get("stats") or {},
        mitre_coverage=idx.get("mitre_coverage") or {},
        items=[MarketplaceItemSummary(**_summarise(i)) for i in items],
        installed_ids=installed_ids,
    )


def _summarise(i: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": i.get("id", ""),
        "type": i.get("type", "detection"),
        "name": i.get("name") or i.get("id", ""),
        "description": (i.get("description") or "").strip(),
        "version": i.get("version", "1.0.0"),
        "severity": i.get("severity"),
        "category": i.get("category"),
        "source": i.get("source") or "core",
        "verified": bool(i.get("verified")),
        "sdks": list(i.get("sdks") or []),
        "mitre_techniques": list(i.get("mitre_techniques") or []),
        "tags": list(i.get("tags") or []),
    }


@router.post("/install", response_model=InstallResponse)
async def install_marketplace_item(
    body: InstallRequest,
    current_user: Annotated[AuthUser, Depends(require_permission("settings:write"))],
    db: TenantDBSession,
) -> InstallResponse:
    """Activate a marketplace item for the caller's tenant.

    For core (on-disk) items this records that the item is "enabled"
    for the tenant — the underlying detection/playbook/plugin file is
    already present on the AiSOC instance and is read straight from disk
    by the relevant subsystem. The install marker is what the UI needs
    in order to show ``✓ Installed`` and what tenants can later disable.
    """
    idx = _load_index()
    match: dict[str, Any] | None = None
    for it in idx.get("items") or []:
        if it.get("type") == body.type and it.get("id") == body.id:
            match = it
            break
    if not match:
        raise HTTPException(
            status_code=404,
            detail=f"Marketplace item not found: {body.type}:{body.id}",
        )

    # 4,388 of the 7,155 catalogue entries are rules the detection engine does
    # not load. Installing one flips a per-tenant flag over a rule that can
    # never match, which is a no-op wearing the costume of an action. The
    # console says "Cannot install" and offers no button — but that was the
    # only thing stopping it: a POST straight at this route installed a
    # reference-only rule and answered 200, so the control was styled as
    # prevented rather than prevented. The catalogue decides, not the caller.
    if match.get("executable") is False:
        raise HTTPException(
            status_code=409,
            detail=(
                f"{body.type}:{body.id} is reference-only — the detection engine does not "
                "load it, so installing it would enable nothing."
                + (f" Reason: {match['quarantine_reason']}" if match.get("quarantine_reason") else "")
            ),
        )

    sha = _content_sha256(match)

    tenant_id = str(current_user.tenant_id)
    user_email = current_user.email or str(current_user.user_id)

    installed_at, already = await marketplace_installs.record_install(
        db,
        tenant_id=tenant_id,
        item_id=body.id,
        item_type=body.type,
        version=str(match.get("version") or ""),
        content_sha256=sha,
        installed_by=current_user.user_id,
    )

    return InstallResponse(
        id=body.id,
        type=body.type,
        name=str(match.get("name") or body.id),
        version=str(match.get("version") or ""),
        content_sha256=sha,
        installed_at=installed_at.isoformat(),
        installed_by=user_email,
        already_installed=already,
    )


@router.delete("/install")
async def uninstall_marketplace_item(
    type: Literal["detection", "playbook", "plugin"],
    id: str,
    current_user: Annotated[AuthUser, Depends(require_permission("settings:write"))],
    db: TenantDBSession,
) -> dict[str, Any]:
    """Remove a previously installed marketplace item from the tenant."""
    tenant_id = str(current_user.tenant_id)
    removed = await marketplace_installs.remove_install(db, tenant_id=tenant_id, item_id=id)
    if not removed:
        raise HTTPException(
            status_code=404,
            detail=f"Item not installed for this tenant: {type}:{id}",
        )
    return {"status": "uninstalled", "id": id, "type": type}


@router.get("/installed")
async def list_installed(
    current_user: AuthUser,
    db: TenantDBSession,
) -> dict[str, Any]:
    """List all marketplace items installed for the caller's tenant."""
    rows = await db.execute(
        text("""
            SELECT item_id, item_type, version, image_digest, installed_at
              FROM marketplace_installs
             WHERE tenant_id = CAST(:t AS uuid)
             ORDER BY item_type, item_id
        """).bindparams(t=str(current_user.tenant_id))
    )
    items = [
        {
            "id": r[0],
            "type": r[1],
            "version": r[2],
            "content_sha256": r[3],
            "installed_at": r[4].isoformat() if r[4] else None,
        }
        for r in rows.all()
    ]
    return {"total": len(items), "items": items}


@router.get("/mitre")
async def mitre_coverage(
    current_user: AuthUser,
) -> dict[str, Any]:
    """Return the MITRE ATT&CK coverage block from the marketplace index.

    Useful for the marketplace UI to render its MITRE filter without
    walking every item on the client.
    """
    idx = _load_index()
    coverage = idx.get("mitre_coverage") or {
        "techniques": {},
        "unique_techniques": 0,
        "total_with_mitre": 0,
    }
    return coverage
