import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "intro",
        "installation",
        "quickstart",
        "architecture",
        "benchmark",
        "benchmark-methodology",
        "benchmark-scoreboard",
        "evaluation/replay",
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        "concepts/capabilities",
        "concepts/multi-tenancy",
        "concepts/cases",
        "concepts/playbooks",
        "concepts/detections",
        "concepts/python-detections",
        "concepts/windowed-detections",
        "concepts/ai-estate",
        "concepts/groundedness",
        "concepts/live-actions",
        "concepts/retro-hunts",
        "concepts/hunting-agent",
        "concepts/automation-maturity",
        "concepts/self-play",
        "concepts/investigation-swarm",
        "concepts/compounding-memory",
        "concepts/model-router",
        "concepts/llmops",
      ],
    },
    {
      type: "category",
      label: "Features",
      items: [
        "features/connector-health",
        "features/data-pipeline",
        "features/attack-path-agent",
      ],
    },
    {
      type: "category",
      label: "Console",
      items: [
        "console/getting-started",
        "console/funnel-kpis",
        "console/queue",
        "console/rule-tuning",
        "console/investigation-rail",
        "console/public-replay",
        "console/tenant-skills",
        "console/triage-context",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      items: [
        "architecture/overview",
        "architecture/agents",
        "architecture/graph-schema",
        "architecture/itsm-as-source-of-truth",
      ],
    },
    {
      type: "category",
      label: "Connectors",
      items: [
        // BEGIN GENERATED CONNECTOR LIST
        "connectors/index",
        "connectors/hello-connector",
        "connectors/endpoint-decision-matrix",
        "connectors/api-coverage",
        "connectors/universal-capture",
        "connectors/osquery-extensions",
        "connectors/abnormal_security",
        "connectors/ai-gateway",
        "connectors/auditd",
        "connectors/auth0",
        "connectors/aws-cloudtrail",
        "connectors/aws-guardduty",
        "connectors/aws-security-hub",
        "connectors/aws-vpc-flow",
        "connectors/azure-activity",
        "connectors/azure-defender",
        "connectors/azure-entra",
        "connectors/box",
        "connectors/carbon-black",
        "connectors/chronicle",
        "connectors/cisco-umbrella",
        "connectors/cloudflare",
        "connectors/cloudflare-zt",
        "connectors/confluence-audit",
        "connectors/cortex-xdr",
        "connectors/cortex-xsiam",
        "connectors/crowdstrike",
        "connectors/darktrace",
        "connectors/datadog",
        "connectors/datadog-cloud-siem",
        "connectors/devo",
        "connectors/dropbox",
        "connectors/duo-security",
        "connectors/elastic",
        "connectors/email-inbox",
        "connectors/exabeam",
        "connectors/falco",
        "connectors/fleetdm",
        "connectors/gcp-cloud-audit",
        "connectors/gcp-scc",
        "connectors/github",
        "connectors/gitlab",
        "connectors/google-workspace",
        "connectors/greynoise",
        "connectors/imperva",
        "connectors/jira",
        "connectors/jumpcloud",
        "connectors/kubernetes-audit",
        "connectors/lacework",
        "connectors/llm_usage",
        "connectors/m365-audit",
        "connectors/microsoft-sentinel",
        "connectors/mimecast",
        "connectors/netskope",
        "connectors/oci",
        "connectors/okta",
        "connectors/onepassword",
        "connectors/opsgenie",
        "connectors/orca",
        "connectors/osctrl",
        "connectors/pagerduty",
        "connectors/prisma-cloud",
        "connectors/proofpoint",
        "connectors/qradar",
        "connectors/qualys",
        "connectors/rapid7-insightidr",
        "connectors/salesforce",
        "connectors/securonix",
        "connectors/sentinelone",
        "connectors/servicenow",
        "connectors/slack-audit",
        "connectors/snowflake",
        "connectors/snyk",
        "connectors/splunk",
        "connectors/sublime_security",
        "connectors/sumo-logic",
        "connectors/sysdig",
        "connectors/syslog_cef",
        "connectors/tailscale",
        "connectors/tenable-io",
        "connectors/tines",
        "connectors/torq",
        "connectors/trellix-helix",
        "connectors/trend-vision-one",
        "connectors/vault",
        "connectors/wazuh",
        "connectors/windows_event",
        "connectors/wiz",
        "connectors/zeek_suricata",
        "connectors/zscaler",
        // END GENERATED CONNECTOR LIST
      ],
    },
    {
      type: "category",
      label: "Detections",
      items: ["detections/coverage", "detections/hello-hunt"],
    },
    {
      type: "category",
      label: "Benchmarks",
      items: ["benchmarks/alert-reduction"],
    },
    {
      type: "category",
      label: "Operations",
      items: [
        "operations/security",
        "operations/enterprise-sso",
        "operations/data-governance",
        "compliance/evidence-pack",
        "compliance/fips-posture",
        "operations/credentials",
        "operations/where-the-model-runs",
        "operations/secrets",
        "operations/scim",
        "operations/case-orchestration",
        "operations/alert-prioritisation",
        "operations/detection-lifecycle",
        "operations/white-label",
        "operations/usage-metering",
        "operations/ingest-authentication",
        "operations/airgap",
        "operations/air-gapped",
        "operations/sandbox-providers",
        "operations/llm-gateway",
        "operations/llm-cost",
        "operations/mcp-client",
        "operations/codespaces",
        "operations/theming",
        "operations/ha-deployment",
        "operations/backup-and-restore",
        "operations/performance",
        "operations/release-policy",
        "operations/upgrades",
        "operations/notifications",
        "operations/action-approvals",
        "operations/agent-vendor-tools",
        "operations/shadow-mode",
        "operations/case-reports",
        "operations/troubleshooting",
        "operations/faq",
        "operations/adoption-questions",
        "operations/managed-instance",
      ],
    },
    {
      type: "category",
      label: "Migrating to AiSOC",
      items: ["migration/from-splunk"],
    },
    {
      type: "category",
      label: "Plugin SDK",
      items: [
        "plugins/overview",
        "plugins/python-sdk",
        "plugins/hello-plugin",
        "plugins/go-sdk",
        "plugins/publishing",
        "plugins/cli",
        "plugins/lifecycle",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      items: ["integrations/mcp", "integrations/siem-writeback", "integrations/misp-push", "integrations/github-action"],
    },
    {
      type: "category",
      label: "API Reference",
      items: ["api/rest", "api/graphql", "api/websocket"],
    },
    {
      type: "category",
      label: "Deployment",
      items: [
        "deployment/docker",
        "deployment/walkthrough",
        "deployment/single-host",
        "deployment/kubernetes",
        "deployment/gcp",
        "deployment/azure",
        "deployment/env-vars",
      ],
    },
    {
      type: "category",
      label: "Contributing",
      items: ["contributing/dev-setup", "contributing/guidelines", "contributing/reproducible-builds"],
    },
    "glossary",
  ],
};

export default sidebars;
