// AUTO-GENERATED by scripts/generate_corpus_stats.py.
// Do not edit by hand. Run the script (or `make corpus-stats`) instead.
//
// Single source of truth for every published detection / marketplace count.
//
// EXECUTABLE_DETECTION_COUNT is the capability number: rules the fusion
// engine actually loads. DETECTIONS_ON_DISK is the indexed corpus, most of
// which is quarantined and never evaluated -- it is a corpus figure and must
// never be presented as what the product executes.

import data from './corpus-stats.json';

/** Rules the fusion engine loads and evaluates. */
export const EXECUTABLE_DETECTION_COUNT: number = data.executable;

/** Detection YAML indexed in the marketplace, quarantined rules included. */
export const DETECTIONS_ON_DISK: number = data.onDisk;

/** Imported rules held under `_quarantine/`: on disk, never loaded. */
export const QUARANTINED_DETECTIONS: number = data.quarantined;

export const PLUGIN_COUNT: number = data.plugins;

/** Playbooks in the shipped v1 pack. Not every indexed playbook: the
 *  standalone response playbooks under `detections/playbooks/` are
 *  playbooks and are not part of the pack, so a surface saying "packs"
 *  must read this and one saying "playbooks" must read the total. */
export const PLAYBOOK_PACK_COUNT: number = data.playbookPacks;

/** Every playbook the marketplace indexes, pack and standalone. */
export const PLAYBOOK_COUNT: number = data.playbooks;
export const MARKETPLACE_ITEM_COUNT: number = data.marketplaceItems;

/** Executable rules per detection category. */
export const DETECTION_CATEGORIES: Readonly<Record<string, number>> = data.categories;
export const DETECTION_CATEGORY_COUNT: number = Object.keys(data.categories).length;

/** Locale-formatted labels, so no surface re-implements the separator. */
export const EXECUTABLE_DETECTIONS_LABEL = `${EXECUTABLE_DETECTION_COUNT.toLocaleString()} executable detections`;
export const MARKETPLACE_ITEMS_LABEL = `${MARKETPLACE_ITEM_COUNT.toLocaleString()} marketplace items`;
