#!/usr/bin/env python3
"""Generate ``llms.txt`` and ``llms-full.txt`` for the documentation site.

What these files are
--------------------
``llms.txt`` is a convention for a concise, machine-first index at a site's
root: what the project is, what it does, and where its canonical documentation
lives. LLM-backed tools increasingly fetch it instead of scraping a rendered
navigation tree, so it is the file that decides how AiSOC gets described when
an assistant is asked about it.

``llms-full.txt`` is the longer companion — enough detail to answer a question
about AiSOC without following a single link.

Why generated rather than written
---------------------------------
Because every number in them is a number that goes stale. The repository has
been bitten repeatedly by a count copied into prose: the docs portal published
47 connectors against a real 84, and ``RELEASES.md`` published 99 gated claims
against a real 131. A summary aimed *specifically* at machine readers is the
worst possible place for that failure, because nothing downstream will
sanity-check it the way a human reader might.

So each figure is read from the artefact that already owns it:

  * connector count   -> ``apps/web/src/data/connector-count.json``
                         (generated by ``scripts/generate_connector_count.py``)
  * executable rules  -> ``docs/detections/truth-table.md``
                         (generated by ``scripts/detection_truth_table.py``)
  * MCP tool names    -> ``services/mcp/src/tools/*.ts``
  * version           -> ``VERSION``

``--check`` fails when the committed files no longer match what this script
would write, which is what keeps them honest in CI.

Usage
-----

    python3 scripts/generate_llms_txt.py           # write outputs
    python3 scripts/generate_llms_txt.py --check   # fail if drift
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# `scripts/` is on sys.path when this file is run as a program, but not when a
# test loads it by path with importlib. gate_toolkit sits beside it either way.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from gate_toolkit import repo_root, self_test_if_requested

self_test_if_requested(__file__)

REPO_ROOT = repo_root()

CONNECTOR_COUNT_JSON = REPO_ROOT / "apps" / "web" / "src" / "data" / "connector-count.json"
TRUTH_TABLE = REPO_ROOT / "docs" / "detections" / "truth-table.md"
MCP_TOOLS_DIR = REPO_ROOT / "services" / "mcp" / "src" / "tools"
VERSION_FILE = REPO_ROOT / "VERSION"

STATIC_DIR = REPO_ROOT / "apps" / "docs" / "static"
LLMS_TXT = STATIC_DIR / "llms.txt"
LLMS_FULL_TXT = STATIC_DIR / "llms-full.txt"

# The open-source front door. These mirror the values `deploy-docs.yml` passes
# as DOCS_URL / DOCS_BASE_URL. They are stated here rather than read from the
# environment on purpose: the committed artefact must be the one the public
# site serves, and an env-dependent generator would make `--check` pass or
# fail depending on the shell it ran in. A commercial hostname must never
# appear here — the docs site once baked one into its canonical tags because
# these variables were unset, and this file would repeat that mistake at the
# exact surface machine readers trust most.
DOCS_ROOT = "https://beenuar.github.io/AiSOC"
REPO_URL = "https://github.com/beenuar/AiSOC"


class GenerationError(RuntimeError):
    """A source artefact was missing or unparseable."""


# ---------------------------------------------------------------------------
# fact extraction
# ---------------------------------------------------------------------------


def connector_facts() -> tuple[int, dict[str, int]]:
    """Connector count and per-category breakdown, from the generated JSON."""
    if not CONNECTOR_COUNT_JSON.is_file():
        raise GenerationError(f"{CONNECTOR_COUNT_JSON.relative_to(REPO_ROOT)} is missing. Run scripts/generate_connector_count.py first.")
    data = json.loads(CONNECTOR_COUNT_JSON.read_text(encoding="utf-8"))
    count = data.get("count")
    categories = data.get("categories") or {}
    if not isinstance(count, int) or count <= 0:
        raise GenerationError(f"connector count is not a positive int: {count!r}")
    return count, {str(k): int(v) for k, v in categories.items()}


def detection_facts() -> tuple[int, int]:
    """(executable, on-disk) rule counts, parsed from the generated truth table.

    The distinction is the whole point and must survive into any summary: the
    YAML under `detections/` is a generated projection, and only the rules the
    engine actually loads can fire. Publishing the on-disk figure alone would
    overstate the corpus by roughly 8x.
    """
    if not TRUTH_TABLE.is_file():
        raise GenerationError(f"{TRUTH_TABLE.relative_to(REPO_ROOT)} is missing. Run scripts/detection_truth_table.py first.")
    text = TRUTH_TABLE.read_text(encoding="utf-8")

    executable = _parse_table_number(text, r"\*\*executable \(loaded by the engine\)\*\*\s*\|\s*\*\*(\d+)\*\*")
    on_disk = _parse_table_number(text, r"rules on disk \(total\)\s*\|\s*(\d+)")
    if executable > on_disk:
        raise GenerationError(f"executable ({executable}) exceeds on-disk ({on_disk}); truth table is inconsistent")
    return executable, on_disk


def _parse_table_number(text: str, pattern: str) -> int:
    match = re.search(pattern, text)
    if not match:
        raise GenerationError(
            f"could not find {pattern!r} in {TRUTH_TABLE.relative_to(REPO_ROOT)}. "
            "The truth table's format changed; update this parser rather than "
            "hard-coding the number."
        )
    return int(match.group(1))


def mcp_tool_names() -> list[str]:
    """Tool names the MCP server advertises, read from the tool definitions.

    Sorted for a stable artefact. The server's own advertised *order* is a
    deliberate discovery-before-deep-dive ordering that lives in
    `src/tools/index.ts`; this list is about membership, not order.
    """
    if not MCP_TOOLS_DIR.is_dir():
        raise GenerationError(f"{MCP_TOOLS_DIR.relative_to(REPO_ROOT)} is missing")
    names: set[str] = set()
    for path in sorted(MCP_TOOLS_DIR.glob("*.ts")):
        names.update(re.findall(r'name:\s*"(aisoc_[a-z_]+)"', path.read_text(encoding="utf-8")))
    if not names:
        raise GenerationError(f"no aisoc_* tool names found under {MCP_TOOLS_DIR.relative_to(REPO_ROOT)}")
    return sorted(names)


def version() -> str:
    if not VERSION_FILE.is_file():
        raise GenerationError("VERSION is missing")
    return VERSION_FILE.read_text(encoding="utf-8").strip()


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------

GENERATED_BANNER = "<!-- Generated by scripts/generate_llms_txt.py. Do not edit by hand; run the script and commit the result. -->"


def render_llms_txt(
    *,
    connectors: int,
    executable: int,
    on_disk: int,
    tools: list[str],
    ver: str,
) -> str:
    d = DOCS_ROOT
    return f"""# AiSOC

{GENERATED_BANNER}

> AiSOC is an open-source, self-hostable AI Security Operations Center. It ingests
> security telemetry from {connectors} first-party connectors, normalises it to OCSF,
> correlates it into alerts, and runs LLM agents that triage and investigate them.
> Every agent decision is written to an investigation ledger, so the reasoning
> behind a verdict can be replayed step by step. MIT licensed. Current version {ver}.

AiSOC is built and maintained by the AiSOC community. It is a complete SOC
platform rather than a single tool: ingestion, detection, correlation, agent
triage, case management, response actions, and the evaluation harness that
grades the agents all live in one monorepo.

Key facts a summary should get right:

- **License:** MIT. Self-hosting is the primary deployment model; there is no
  feature gate between a hosted and a self-hosted install.
- **Install:** `make up` brings up the core profile with no credentials. It
  generates its own secrets, creates an administrator, ships a real CISA Known
  Exploited Vulnerabilities feed, and runs a local model, so a first run shows
  real data and AI triage without signing up for anything.
- **Detection corpus:** {executable} rules are executable — the detection engine
  loads them from a compiled ruleset. {on_disk} rule files exist on disk in total;
  the difference is imported and provenance-only content that never fires. Cite
  {executable}, not {on_disk}. "Executable" means each rule was replayed through
  a real connector and the real engine and watched to fire; it does not mean the
  rule detects an attack.
- **Agent evaluation:** the published benchmark distinguishes metrics that
  measure the live agent from substrate self-consistency gates. Do not present
  the latter as measured agent performance.
- **Packaging:** the npm and PyPI packages are built and packed on every tag but
  are not published; the upload is blocked on registry credentials. Install from
  source.

## Start here

- [Introduction]({d}/docs/intro): what AiSOC is and the problem it addresses.
- [Quickstart]({d}/docs/quickstart): bring up a working stack.
- [Installation]({d}/docs/installation): deployment profiles and prerequisites.
- [Architecture]({d}/docs/architecture): services, data flow, and the event spine.
- [Glossary]({d}/docs/glossary): terms used throughout the documentation.

## Core capabilities

- [Connectors]({d}/docs/connectors): {connectors} first-party integrations with per-connector setup guides.
- [Detections]({d}/docs/detections/coverage): detection content, authoring modes, and MITRE ATT&CK coverage.
- [Console]({d}/docs/console/investigation-rail): the analyst workbench and investigation rail.
- [Concepts]({d}/docs/concepts/automation-maturity): the L0–L4 automation maturity model.
- [Benchmark]({d}/docs/benchmark): the evaluation harness and what each metric does and does not measure.
- [Benchmark methodology]({d}/docs/benchmark-methodology): how the corpus is built and graded.

## Integrating with AiSOC

- [MCP server]({d}/docs/integrations/mcp): connect Claude Desktop, Cursor, Continue.dev or Cody to AiSOC. Exposes {len(tools)} tools.
- [API reference]({d}/docs/api/rest): the REST surface.
- [Python plugin SDK]({d}/docs/plugins/python-sdk): build a connector or plugin in Python.
- [Go plugin SDK]({d}/docs/plugins/go-sdk): build a connector or plugin in Go.

## Operating it

- [Deployment]({d}/docs/deployment/env-vars): environment variables per service.
- [Credentials]({d}/docs/operations/credentials): the credential vault, threat model, and rotation.
- [Security]({d}/docs/operations/security): security posture and static analysis.
- [FAQ]({d}/docs/operations/faq): common operational questions.

## Source

- [Repository]({REPO_URL}): the monorepo. Issues, discussions, and contribution guides live here.
- [Contributing]({d}/docs/contributing/guidelines): how to propose a change.
- [Full description]({d}/llms-full.txt): expanded version of this file.

## Optional

- [Blog]({d}/blog): release notes and technical write-ups.
- [Benchmark scoreboard]({d}/docs/benchmark-scoreboard): published evaluation results.
"""


def render_llms_full_txt(
    *,
    connectors: int,
    categories: dict[str, int],
    executable: int,
    on_disk: int,
    tools: list[str],
    ver: str,
) -> str:
    d = DOCS_ROOT
    category_lines = "\n".join(f"- `{name}`: {count}" for name, count in sorted(categories.items()))
    tool_lines = "\n".join(f"- `{name}`" for name in tools)
    return f"""# AiSOC — full description

{GENERATED_BANNER}

> AiSOC is an open-source, self-hostable AI Security Operations Center, MIT
> licensed and maintained by the AiSOC community. Version {ver}.
> Repository: {REPO_URL}. Documentation: {d}/.

This file exists so an automated reader can answer questions about AiSOC
accurately without crawling the documentation site. Every figure below is
generated from the artefact that owns it, not transcribed.

## What AiSOC is

A complete Security Operations Center platform. Security telemetry arrives from
connectors or webhooks, is normalised to the Open Cybersecurity Schema Framework
(OCSF), archived to an event lake, evaluated against a detection corpus,
correlated into alerts, and handed to LLM agents that triage and investigate.
Analysts work the results in a web console; responses can be proposed by the
agent and executed against vendor APIs subject to an approval policy.

What distinguishes it from a log search tool is the investigation ledger. Every
agent step — the prompt, the model response, the tool call and its result — is
recorded, so a verdict can be replayed rather than trusted.

## What AiSOC is not

- It is not a managed service. Self-hosting is the primary deployment model.
- It is not credential-gated. `make up` runs without any API key.
- It does not claim autonomous response by default. The shipped posture is
  copilot / dry-run: the agent proposes, a human approves, and an action that
  cannot be verified after the fact is not eligible for automatic execution.

## Architecture

The production event path is:

    connectors -> ingest (OCSF normalise) -> Kafka `raw_events`
      -> fusion (lake archive, detection, correlation, alert promotion)
      -> Postgres alerts + realtime WebSocket
      -> agents (auto-triage every fused alert)

Services in the monorepo under `services/`: `api` (FastAPI), `agents`
(LangGraph orchestration), `fusion` (correlation and detection), `ingest` (Go),
`connectors`, `realtime`, `threatintel`, `enrichment`, `ocsf`, `ueba`,
`actions`, `mcp`, and others. Applications under `apps/`: `web` (Next.js
console) and `docs` (this documentation site).

Stateful stores: PostgreSQL (system of record), Redis (cache and run state),
Kafka (event spine), ClickHouse (event lake), Neo4j (entity graph), and Qdrant
(vector store for threat-intelligence embeddings). Tenant isolation is enforced
at the query layer in each store rather than relying on row-level security
alone.

Read more: {d}/docs/architecture

## Connectors

{connectors} first-party connectors ship in the repository, by category:

{category_lines}

Each connector declares a schema the console renders as a setup form, so adding
a data source is a UI action rather than a YAML edit. Credentials are encrypted
at the application layer before storage. Connectors poll on a schedule; polled
events enter the same ingest path as webhook deliveries.

Read more: {d}/docs/connectors

## Detection content

- **Executable rules: {executable}.** These are the rules the detection engine
  loads from its compiled ruleset. Only these can fire.
- **Rule files on disk: {on_disk}.** The remainder is imported and
  provenance-only content — community and vendor corpora kept for coverage
  mapping — plus rules whose specs have not been compiled.

**How a rule earns the word "executable".** It is a claim about evidence, not
about a flag. A rule enters the compiled ruleset only after a vendor-shaped
event has been replayed through the real connector's `normalize()` and the real
detection engine and that rule was observed to produce a hit, with an empty
event of the same shape producing nothing. Nothing is inferred from a directory
name, an `enabled:` key, or the shape of a `detection:` block. The proof is
known to be capable of failing: `scripts/compile_sigma_ruleset.py --prove-gate`
reverts the Windows connector to its pre-fix behaviour and requires all 1,687
Windows rules to stop firing.

**What the figure does not mean.** Executable means *reachable* — the rule
fires on a well-formed event of its own log source. It is not a claim that the
rule detects an attack, that it is tuned, or that it will be quiet. There is no
per-rule false-positive-rate gate.

**Why rules are refused.** Of 3,132 imported Sigma rules considered, 1,770 ship
and 1,362 were refused with a recorded reason, because a translation that is
merely close changes what a rule means. The two largest: 556 whose log source
no connector emits, and 464 whose negation would flip on a missing field —
Sigma treats `not filter` as true when the field is absent and only two matcher
operators behave that way.

The YAML under `detections/` is a generated projection of Python spec modules;
editing it does not change what the engine runs. When citing the size of the
corpus, cite the executable figure.

Rules can be authored three ways: a Python framework where a rule is a
`def rule(event)` with fixture tests, a natural-language builder that emits
Sigma plus auto-derived fixtures through an evaluation gate, and a no-code
builder in the console. Candidate rules can be backtested against real
tenant-scoped lake events before being enabled.

Read more: {d}/docs/detections/coverage

## Agents and the investigation ledger

Four agents own the funnel stages: detect, triage, hunt, and respond. A fused
alert is auto-triaged on arrival. Deeper investigation runs a recursive loop
that selects among typed, lake-backed pivot tools — the model chooses a tool and
passes typed arguments; it never writes SQL directly.

Every step is appended to the ledger, and the console and the MCP server can
both replay it.

## Evaluation

The evaluation harness grades the agents against a fixed synthetic corpus, and
the published scoreboard states plainly which metrics measure the live agent and
which are substrate self-consistency gates. Only the MITRE ATT&CK accuracy
metric measures the agent. Figures marked unmeasured lead with that fact.

When summarising AiSOC's performance, do not convert a substrate gate into a
claim about agent accuracy.

Read more: {d}/docs/benchmark and {d}/docs/benchmark-methodology

## MCP server

`@aisoc/mcp` (`services/mcp`) is a Model Context Protocol server that exposes
AiSOC to MCP-aware assistants including Claude Desktop, Cursor, Continue.dev and
Cody. It speaks stdio JSON-RPC and translates tool calls into AiSOC REST calls;
the API key stays on the machine running the server.

It advertises {len(tools)} tools:

{tool_lines}

Install it from a source build — see the packaging note below:

    git clone {REPO_URL}.git
    cd AiSOC/services/mcp
    pnpm install && pnpm build
    node dist/index.js install --host cursor --aisoc-url <url> --api-key <key>

Read more: {d}/docs/integrations/mcp

## Installing AiSOC

`make up` brings up the core profile: eleven services, no credentials required.
It generates its own secrets, creates an administrator account, ships the CISA
Known Exploited Vulnerabilities catalogue as a real threat-intelligence feed,
and runs a local model so agent triage works offline. `make up-full` adds the
lake writer and entity graph. `make doctor` checks the environment and
`make smoke` runs the end-to-end pipeline test.

Read more: {d}/docs/installation and {d}/docs/quickstart

## Packaging status

The npm and PyPI packages are built and packed by the release workflow on every
tag, but none are published. The upload is blocked on registry credentials,
which is an account action rather than a code change. Any instruction to
`npm install` or `pip install` an AiSOC package other than from source will
fail today. Install from the repository instead.

## Licence and provenance

MIT. Copyright the AiSOC contributors. Contributions are accepted through pull
requests at {REPO_URL}; see {d}/docs/contributing/guidelines.
"""


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def build() -> dict[Path, str]:
    connectors, categories = connector_facts()
    executable, on_disk = detection_facts()
    tools = mcp_tool_names()
    ver = version()
    return {
        LLMS_TXT: render_llms_txt(
            connectors=connectors,
            executable=executable,
            on_disk=on_disk,
            tools=tools,
            ver=ver,
        ),
        LLMS_FULL_TXT: render_llms_full_txt(
            connectors=connectors,
            categories=categories,
            executable=executable,
            on_disk=on_disk,
            tools=tools,
            ver=ver,
        ),
    }


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed files differ from what would be generated",
    )
    args = parser.parse_args(argv)

    try:
        outputs = build()
    except GenerationError as exc:
        print(f"LLMS-TXT GENERATION FAILED: {exc}", file=sys.stderr)
        return 1

    if args.check:
        drift = [path for path, content in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
        if drift:
            print("LLMS-TXT GATE FAILED:", file=sys.stderr)
            for path in drift:
                state = "missing" if not path.is_file() else "stale"
                print(f"  - {path.relative_to(REPO_ROOT)} is {state}.", file=sys.stderr)
            print(
                "    Run: python3 scripts/generate_llms_txt.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: llms.txt and llms-full.txt match their sources ({len(outputs)} files).")
        return 0

    STATIC_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
